import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import UiProvider from "@/context/ui/ui-context";
import AuthProvider from "@/context/auth/auth-context";

const IRANYekanFont = localFont({
  variable: "--font-iranyekan",
  src: [
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebBold.woff2",
      style: "normal",
      weight: "bold",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebThin.woff2",
      style: "normal",
      weight: "100",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebLight.woff2",
      style: "normal",
      weight: "300",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebRegular.woff2",
      style: "normal",
      weight: "normal",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebMedium.woff2",
      style: "normal",
      weight: "500",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebExtraBlack.woff2",
      style: "normal",
      weight: "800",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebBlack.woff2",
      style: "normal",
      weight: "850",
    },
    {
      path: "../fonts/iranyekan/woff2/IRANYekanWebExtraBlack.woff2",
      style: "normal",
      weight: "900",
    },
  ],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} dir={`rtl`}>
      <body className={`${IRANYekanFont.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <UiProvider>
            <AuthProvider>{children}</AuthProvider>
          </UiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
