export default ({
  id,
  status,
  status_text,
  type,
  type_text,
  first_name,
  last_name,
  full_name,
  email,
  mobile,
  national_code,
  created_at_text,
  deleted_at_text,
}) => ({
  id: id,
  status: status,
  statusText: status_text,
  statusValue: {
    label: status_text,
    value: status,
  },
  type: type,
  typeText: type_text,
  typeValue: {
    label: type_text,
    value: type,
  },
  typeBadgeConfig: {
    1: "default",
    2: "error",
  },
  firstName: first_name,
  lastName: last_name,
  fullName: full_name,
  email: email,
  mobile: mobile,
  nationalCode: national_code,
  createdAtText: created_at_text,
  deletedAtText: deleted_at_text,
});
